# Receita 2: Frontend (React + Vite)
# Stage 1: Compila o React
FROM node:20-alpine AS builder

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./

RUN npm install

COPY frontend/ ./

# Compila (transforma JSX em HTML/CSS/JS normal)
RUN npm run build

# Stage 2: Serve o HTML compilado
FROM nginx:alpine

# Copia o arquivo compilado pra dentro do Nginx
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

# Copia a configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
