server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Serve os arquivos estáticos
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API vai pra cá (passthrough pro backend)
    location /api/ {
        proxy_pass http://backend:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
